import {useEffect, memo} from "react";
import {useInView} from "react-intersection-observer";
import {motion, useAnimation} from "framer-motion";
import Head from "next/head";
import Partnership from "../../components/RAndDCompoenents/Partnership";
import LCA from "../../components/RAndDCompoenents/LCA";
import PartnershipMobile from "../../components/mobileComponents/PartnershipMobile";
import LCAMobile from "../../components/mobileComponents/LCAMobile";

const TansitionVidLToR = {
  visible: {opacity: 1, x: 0, transition: {duration: 0.8}},
  hidden: {opacity: 0, x: -1000},
};

function Randd() {
  const controlText = useAnimation();
  const controlVid = useAnimation();
  const [ref, inView] = useInView();

  useEffect(() => {
    if (inView) {
      controlText.start("visible");
      controlVid.start("visible");
    }
  }, [controlVid, controlText, inView]);

  return (
    <>
      <Head>
        <title>R&D | CNRIKOREA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>

      <div className="mx-[6vw]">
        <div className="relative my-[3vh] mb-[5vh] md:mb-[10vh]">
          <motion.div
            ref={ref}
            className="h-[60vh] sm:h-[80vh]"
            animate={controlVid}
            initial="hidden"
            variants={TansitionVidLToR}>
            <img
              alt="rAnddIntro"
              src="/images/rAnddIntro.jpg"
              className="object-cover h-full w-full rounded-lg shadow-lg"
            />
          </motion.div>
          <motion.div
            ref={ref}
            animate={controlText}
            initial="hidden"
            // variants={TansitionVidRToL}
            className="absolute inset-0 flex justify-center items-center z-10 text-[15vw] md:text-[10vw] font-bold text-white">
            <div>
              <span>R</span>
              <span className="mx-2">&</span>
              <span>D</span>
            </div>
          </motion.div>
        </div>
        <div className="w-[100%] ">
          <div className="text-[8vw] sm:text-[5vw] md:text-[4vw] font-semibold  mb-[2vh]">
            What is LCA?
          </div>
          <div className="hidden sm:flex">
            <LCA />
          </div>
          <div className=" sm:hidden">
            <LCAMobile />
          </div>

          <div className="grid grid-cols-2" />
        </div>
        <div className="w-[100%] mt-[6vh] sm:mt-[12vh]">
          <div className="text-[8vw] sm:text-[5vw] md:text-[4vw] font-semibold  mb-[2vh]">
            Our Work and Partnership
          </div>
          <div className="hidden sm:flex">
            <Partnership />
          </div>
          <div className="sm:hidden">
            <PartnershipMobile />
          </div>
        </div>
      </div>
    </>
  );
}

export default memo(Randd);
