import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { motion, useAnimation } from "framer-motion";
import { useInView } from "react-intersection-observer";
import VerticalTansitionVideoInfo from "../components/LandingComponents.tsx/VerticalTransitionVideoInfo";
import HorizontalTransitionVideoInfo from "../components/LandingComponents.tsx/HorizontalTransitionVideoInfo";
import Box from "../components/Box";
import { LandingContents } from "../functions/LandingContents";
import Link from "next/link";

const Home: NextPage = () => {
  const TansitionVidLToR = {
    vidVisible: { opacity: 1, x: 0, transition: { duration: 0.6 } },
    vidHidden: { opacity: 0, x: -150 },
  
  };

  const TansitionVidRToL = {
    vidVisible: { opacity: 1, x: 0, transition: { duration: 0.6 } },
    vidHidden: { opacity: 0, x: 150 },

  };

  const TansitionVidTToB = {
    vidVisible: { opacity: 1, y: 0, transition: { duration: 0.6 } },
    vidHidden: { opacity: 0, y: -150 },
 
  };

  const TransitionContextLToR = {
    initial: { opacity: 0, x: -100, transition: { duration: 0.6 } },
    open: { opacity: 1, x: 0, transition: { duration: 0.6 } },
    close: { opacity: 0, transition: { duration: 0.6 } },
    close2: { x: -100, transition: { duration: 0 } },

  }

  const TransitionContextRToL = {
    initial: { opacity: 0, x: 200, transition: { duration: 0.6 } },
    open: { opacity: 1, x: 0, transition: { duration: 0.6 } },
    close: { opacity: 0, transition: { duration: 0.6 } },
    close2: { x: 200, transition: { duration: 0 } },
  }

  const TransitionContextTToB = {
    initial: { opacity: 0, y: -80, transition: { duration: 0.6 } },
    open: { opacity: 1, y: 0, transition: { duration: 0.6 } },
    close: { opacity: 0, transition: { duration: 0.6 } },
    close2: { y: -80, transition: { duration: 0 } },
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-slate-200 mx-16 ">
        <div className="pt-10">
          <div className="flex justify-center font-bold text-7xl">
            넷제로 달성을 위해 필요한
          </div>
          <div className="flex justify-center pt-2 font-bold text-7xl">
            Actionable Plan의 모든 것
          </div>
          <div className="flex justify-center pt-4 font-semibold text-xl">
            넷제로 달성을 위해 필요한 Actionable Plan의 모든 것
          </div>
        </div>
        <div className="flex justify-center pt-10">
          <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold  px-4 rounded-full mx-4 w-[15%] h-12">
            체험하기
          </button>
          <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold  px-4 rounded-full mx-4 w-[15%] h-12">
            데모신청
          </button>
        </div>
        <div className="flex justify-center">
          <img
            src="https://watershed.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fhero.f2c8f15e.png&w=1920&q=75"
            className="w-[63%] mt-4 "
          />
        </div>
      </div>

      <section className="sticky inset-x-0 top-[72px] left-0 flex justify-center border-2 w-[100%] bg-white z-50 opacity-90">
        <Link href="#measure">
          <a className="p-4 px-12 cursor-pointer">Measure</a>
        </Link>

        <Link href="#reduce">
          <a className="p-4 px-12 cursor-pointer">Reduce</a>
        </Link>

        <Link href="#remove">
          <a className="p-4 px-12 cursor-pointer">Remove</a>
        </Link>

        <Link href="#report">
          <a className="p-4 px-12 cursor-pointer">Report</a>
        </Link>
      </section>

      <main>
        {/* MEASURE SECTION*/}
        <div id="measure" className=" mx-16 text-5xl">
          Measure
        </div>
        <div className="mx-16 grid grid-cols-2 gap-14 my-4">
          <VerticalTansitionVideoInfo
            imagePosition="top"
            moveFrom={TansitionVidLToR}
            contentInfo={LandingContents.Measure.content1}
          />
          <div>
            <HorizontalTransitionVideoInfo
              imagePosition="right"
              moveFrom={TansitionVidRToL}
              contentInfo={LandingContents.Measure.content2}
            />
            <HorizontalTransitionVideoInfo
              imagePosition="left"
              moveFrom={TansitionVidLToR}
              contentInfo={LandingContents.Measure.content3}
            />
          </div>
        </div>

        {/* REDUCE SECTION*/}
        <div id="reduce" className=" mx-16 text-5xl">
          Reduce
        </div>
        <div className="mx-16 grid grid-cols-2 gap-14 my-4">
          <div>
            <HorizontalTransitionVideoInfo
              imagePosition="right"
              moveVidFrom={TansitionVidRToL}
              moveContextFrom = {TransitionContextLToR}
              contentInfo={LandingContents.Reduce.content1}
            />
            <HorizontalTransitionVideoInfo
              imagePosition="left"
              moveVidFrom={TansitionVidLToR}
              moveContextFrom = {TransitionContextLToR}
              contentInfo={LandingContents.Reduce.content2}
            />
          </div>
          <VerticalTansitionVideoInfo
            imagePosition="top"
            moveFrom={TansitionVidRToL}
            contentInfo={LandingContents.Reduce.content3}
          />
        </div>

        {/* REMOVE SECTION*/}
        <div id="remove" className=" mx-16 text-5xl">
          Remove
        </div>
        <div className="mx-16">
          <HorizontalTransitionVideoInfo
            imagePosition="left"
            moveVidFrom={TansitionVidLToR}
            moveContextFrom = {TransitionContextLToR}
            contentInfo={LandingContents.Remove.content1}
          />
          <HorizontalTransitionVideoInfo
            imagePosition="right"
            moveVidFrom={TansitionVidRToL}
            moveContextFrom = {TransitionContextLToR}
            contentInfo={LandingContents.Measure.content1}
          />
        </div>

        {/* REPORT SECTION*/}
        <div id="report" className=" mx-16 text-5xl">
          Report
        </div>
        <div className="mx-16 grid grid-cols-2 gap-14 my-4">
          <VerticalTansitionVideoInfo
            imagePosition="top"
            moveFrom={TansitionVidLToR}
            contentInfo={LandingContents.Measure.content1}
          />
          <VerticalTansitionVideoInfo
            imagePosition="top"
            moveFrom={TansitionVidRToL}
            contentInfo={LandingContents.Measure.content1}
          />
        </div>
      </main>

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </>
  );
};

export default Home;
